"""empty message

Revision ID: 1112d5ff82b9
Revises: 
Create Date: 2025-01-02 02:30:16.185380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1112d5ff82b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fakulte',
    sa.Column('adi', sa.String(length=255), nullable=False),
    sa.Column('adres', sa.String(length=255), nullable=False),
    sa.Column('telefon', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fakulte_adi'), 'fakulte', ['adi'], unique=False)
    op.create_index(op.f('ix_fakulte_adres'), 'fakulte', ['adres'], unique=False)
    op.create_index(op.f('ix_fakulte_telefon'), 'fakulte', ['telefon'], unique=False)
    op.create_table('bolum',
    sa.Column('adi', sa.String(length=255), nullable=False),
    sa.Column('adres', sa.String(length=255), nullable=False),
    sa.Column('telefon', sa.String(length=255), nullable=False),
    sa.Column('fakulte_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fakulte_id'], ['fakulte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bolum_adi'), 'bolum', ['adi'], unique=False)
    op.create_index(op.f('ix_bolum_adres'), 'bolum', ['adres'], unique=False)
    op.create_index(op.f('ix_bolum_telefon'), 'bolum', ['telefon'], unique=False)
    op.create_table('ogrenci',
    sa.Column('tckimlik_no', sa.String(length=11), nullable=False),
    sa.Column('adi', sa.String(length=255), nullable=False),
    sa.Column('soyadi', sa.String(length=255), nullable=False),
    sa.Column('numara', sa.String(length=255), nullable=False),
    sa.Column('cinsiyet', sa.String(length=1), nullable=False),
    sa.Column('dogumyeriplakasi', sa.Integer(), nullable=False),
    sa.Column('bolum_id', sa.Uuid(), nullable=False),
    sa.Column('dogumTarihi', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bolum_id'], ['bolum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ogrenci_adi'), 'ogrenci', ['adi'], unique=False)
    op.create_index(op.f('ix_ogrenci_cinsiyet'), 'ogrenci', ['cinsiyet'], unique=False)
    op.create_index(op.f('ix_ogrenci_numara'), 'ogrenci', ['numara'], unique=False)
    op.create_index(op.f('ix_ogrenci_soyadi'), 'ogrenci', ['soyadi'], unique=False)
    op.create_index(op.f('ix_ogrenci_tckimlik_no'), 'ogrenci', ['tckimlik_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ogrenci_tckimlik_no'), table_name='ogrenci')
    op.drop_index(op.f('ix_ogrenci_soyadi'), table_name='ogrenci')
    op.drop_index(op.f('ix_ogrenci_numara'), table_name='ogrenci')
    op.drop_index(op.f('ix_ogrenci_cinsiyet'), table_name='ogrenci')
    op.drop_index(op.f('ix_ogrenci_adi'), table_name='ogrenci')
    op.drop_table('ogrenci')
    op.drop_index(op.f('ix_bolum_telefon'), table_name='bolum')
    op.drop_index(op.f('ix_bolum_adres'), table_name='bolum')
    op.drop_index(op.f('ix_bolum_adi'), table_name='bolum')
    op.drop_table('bolum')
    op.drop_index(op.f('ix_fakulte_telefon'), table_name='fakulte')
    op.drop_index(op.f('ix_fakulte_adres'), table_name='fakulte')
    op.drop_index(op.f('ix_fakulte_adi'), table_name='fakulte')
    op.drop_table('fakulte')
    # ### end Alembic commands ###
